# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseSampleCodeForUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
	pod 'Firebase/Storage'
	pod 'Firebase/Auth'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Firebase/Functions'
	pod 'FirebaseFirestoreSwift', '~> 0.2'

  # etc
	pod 'CropViewController'

end
